"""
=========================================================
PharmaGuard AI
PDF Export Utilities
=========================================================
Enterprise Edition v3
=========================================================
"""

from __future__ import annotations

from io import BytesIO

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (

    SimpleDocTemplate,

    Paragraph,

    Spacer

)

# ==========================================================
# PDF REPORT
# ==========================================================

def export_prediction_pdf(

    drug_name: str,

    manufacturer: str,

    risk_score: float,

    risk_level: str,

    priority: str,

    recommendations: list[str]

) -> bytes:
    """
    Generate Prediction PDF Report.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(

        buffer

    )

    styles = getSampleStyleSheet()

    elements = []

    # ======================================================
    # TITLE
    # ======================================================

    elements.append(

        Paragraph(

            "<b>PharmaGuard AI</b>",

            styles["Title"]

        )

    )

    elements.append(

        Paragraph(

            "AI Prediction Report",

            styles["Heading2"]

        )

    )

    elements.append(

        Spacer(

            1,

            20

        )

    )

    # ======================================================
    # INFORMATION
    # ======================================================

    elements.append(

        Paragraph(

            f"<b>Drug:</b> {drug_name}",

            styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

            f"<b>Manufacturer:</b> {manufacturer}",

            styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

            f"<b>Risk Score:</b> {risk_score}",

            styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

            f"<b>Risk Level:</b> {risk_level}",

            styles["BodyText"]

        )

    )

    elements.append(

        Paragraph(

            f"<b>Priority:</b> {priority}",

            styles["BodyText"]

        )

    )

    elements.append(

        Spacer(

            1,

            15

        )

    )

    # ======================================================
    # RECOMMENDATIONS
    # ======================================================

    elements.append(

        Paragraph(

            "<b>Recommendations</b>",

            styles["Heading2"]

        )

    )

    for item in recommendations:

        elements.append(

            Paragraph(

                f"• {item}",

                styles["BodyText"]

            )

        )

    elements.append(

        Spacer(

            1,

            20

        )

    )

    # ======================================================
    # FOOTER
    # ======================================================

    elements.append(

        Paragraph(

            "Generated by PharmaGuard AI",

            styles["Italic"]

        )

    )

    doc.build(

        elements

    )

    pdf = buffer.getvalue()

    buffer.close()

    return pdf


# ==========================================================
# EXPORTS
# ==========================================================

__all__ = [

    "export_prediction_pdf"

]